# Generated by Django 5.1.3 on 2024-11-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_epic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.tasks')),
                ('table2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.epic')),
            ],
        ),
    ]
