# Generated by Django 5.1.3 on 2024-11-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_rename_restaurant_tasks_epic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epic',
            old_name='restaurants',
            new_name='tasks',
        ),
    ]
